version: "3.1"

services:
  mongodb:
    image: mongo
    expose:
      - "27017"
    volumes:
      - ~/.docker/newsdb/mongo:/data/db
  api:
    build: .
    volumes:
      - ./:/srv/app
    expose:
      - "3000"
    depends_on:
      - mongodb
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:3000
      - 443:443
    depends_on:
      - api
