version: "3.1"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/.docker/newsdb/mongo:/data/db
  api:
    build: .
    volumes:
      - ./:/srv/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb
